#pragma once

#include "WindowModule.h"

#include <LuaIntf.h>

using namespace LuaIntf;

namespace SamEngine
{
    inline static void OpenWindowModule(LuaState state)
    {
        LuaBinding(state).beginModule("SamEngine")
            .addProperty("Window", &GetWindow)
            .beginClass<IWindow>("IWindow")
                .addFunction("SetMouseInputCallback", &IWindow::SetMouseInputCallback, LUA_ARGS(MouseInputCallback))
                .addFunction("SetKeyboardInputCallback", &IWindow::SetKeyboardInputCallback, LUA_ARGS(KeyboardInputCallback))
                .addFunction("SetTitle", &IWindow::SetTitle, LUA_ARGS(std::string))
            .endClass()
            .beginClass<MouseButtonType>("MouseType")
                .addConstant("LEFT", MouseButtonType::LEFT)
                .addConstant("RIGHT", MouseButtonType::RIGHT)
                .addConstant("MIDDLE", MouseButtonType::MIDDLE)
            .endClass()
            .beginClass<KeyboardButtonType>("KeyType")
                .addConstant("UNKNOWN", KeyboardButtonType::UNKNOWN)
                .addConstant("ESC", KeyboardButtonType::ESC)
                .addConstant("F1", KeyboardButtonType::F1)
                .addConstant("F2", KeyboardButtonType::F2)
                .addConstant("F3", KeyboardButtonType::F3)
                .addConstant("F4", KeyboardButtonType::F4)
                .addConstant("F5", KeyboardButtonType::F5)
                .addConstant("F6", KeyboardButtonType::F6)
                .addConstant("F7", KeyboardButtonType::F7)
                .addConstant("F8", KeyboardButtonType::F8)
                .addConstant("F9", KeyboardButtonType::F9)
                .addConstant("F10", KeyboardButtonType::F10)
                .addConstant("F11", KeyboardButtonType::F11)
                .addConstant("F12", KeyboardButtonType::F12)
                .addConstant("NUM_1", KeyboardButtonType::NUM_1)
                .addConstant("NUM_2", KeyboardButtonType::NUM_2)
                .addConstant("NUM_3", KeyboardButtonType::NUM_3)
                .addConstant("NUM_4", KeyboardButtonType::NUM_4)
                .addConstant("NUM_5", KeyboardButtonType::NUM_5)
                .addConstant("NUM_6", KeyboardButtonType::NUM_6)
                .addConstant("NUM_7", KeyboardButtonType::NUM_7)
                .addConstant("NUM_8", KeyboardButtonType::NUM_8)
                .addConstant("NUM_9", KeyboardButtonType::NUM_9)
                .addConstant("NUM_0", KeyboardButtonType::NUM_0)
                .addConstant("NUM_PAD_1", KeyboardButtonType::NUM_PAD_1)
                .addConstant("NUM_PAD_2", KeyboardButtonType::NUM_PAD_2)
                .addConstant("NUM_PAD_3", KeyboardButtonType::NUM_PAD_3)
                .addConstant("NUM_PAD_4", KeyboardButtonType::NUM_PAD_4)
                .addConstant("NUM_PAD_5", KeyboardButtonType::NUM_PAD_5)
                .addConstant("NUM_PAD_6", KeyboardButtonType::NUM_PAD_6)
                .addConstant("NUM_PAD_7", KeyboardButtonType::NUM_PAD_7)
                .addConstant("NUM_PAD_8", KeyboardButtonType::NUM_PAD_8)
                .addConstant("NUM_PAD_9", KeyboardButtonType::NUM_PAD_9)
                .addConstant("NUM_PAD_0", KeyboardButtonType::NUM_PAD_0)
                .addConstant("A", KeyboardButtonType::A)
                .addConstant("B", KeyboardButtonType::B)
                .addConstant("C", KeyboardButtonType::C)
                .addConstant("D", KeyboardButtonType::D)
                .addConstant("E", KeyboardButtonType::E)
                .addConstant("F", KeyboardButtonType::F)
                .addConstant("G", KeyboardButtonType::G)
                .addConstant("H", KeyboardButtonType::H)
                .addConstant("I", KeyboardButtonType::I)
                .addConstant("J", KeyboardButtonType::J)
                .addConstant("K", KeyboardButtonType::K)
                .addConstant("L", KeyboardButtonType::L)
                .addConstant("M", KeyboardButtonType::M)
                .addConstant("N", KeyboardButtonType::N)
                .addConstant("O", KeyboardButtonType::O)
                .addConstant("P", KeyboardButtonType::P)
                .addConstant("Q", KeyboardButtonType::Q)
                .addConstant("R", KeyboardButtonType::R)
                .addConstant("S", KeyboardButtonType::S)
                .addConstant("T", KeyboardButtonType::T)
                .addConstant("U", KeyboardButtonType::U)
                .addConstant("V", KeyboardButtonType::V)
                .addConstant("W", KeyboardButtonType::W)
                .addConstant("X", KeyboardButtonType::X)
                .addConstant("Y", KeyboardButtonType::Y)
                .addConstant("Z", KeyboardButtonType::Z)
            .endClass()
        .endModule();
    }
}